[client]
showErrorDetails = true
showSidebarNavigation = false
toolbarMode = "minimal"

[logger]
level = "error"

[ui]
hideTopBar = true

[theme]
base              = "light"
primaryColor      = "#31704f"
backgroundColor   = "#f2f5f1"
secondaryBackgroundColor = "#ffffff"
textColor         = "#25342b"
font              = "sans serif"
